name: BlockLookup
version: '1.0-SNAPSHOT'
main: nl.amk.blocklookup.BlockLookup
api-version: '1.20'
commands:
  blocklookup:
    description: Lookup logs and rollback block actions
    aliases: [bl]
    usage: /<command> <lookup|chat|rollback|restore>
permissions:
  blocklookup.lookup:
    default: op
  blocklookup.chat:
    default: op
  blocklookup.rollback:
    default: op
  blocklookup.restore:
    default: op
